backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter
media_folder: "src/static/img"
public_folder: "/static/img"
logo_url: https://i.imgur.com/GKyRb6S.png

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Blog"
    name: "blog"
    folder: "src/posts"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Titulo", name: "title", widget: "string" }
      - { label: "Descripcion", name: "description", widget: "string" }
      - { label: "Autor", name: "author", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Contenido", name: "body", widget: "markdown" }
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        create: true
        options: ["Tags", "created", "from", "config.yml"]
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Menu"
        name: "items"
        file: "src/_data/navigation.yaml"
        fields:
          - label: Nav Items
            name: items
            widget: list
            allow_add: true
            collapsed: false
            fields:
              - { label: Titulo, name: text, widget: string }
              - { label: URL, name: url, widget: string }
      - label: "Links Principales"
        name: "links"
        file: "src/_data/quicklinks.yaml"
        fields:
          - label: Nav Items
            name: links
            widget: list
            collapsed: false
            fields:
              - { label: Titulo, name: title, widget: string }
              - { label: URL, name: url, widget: string }
              - { label: Thumbnail, name: thumbnail, widget: image, choose_url: true}
              - { label: Description, name: desc, widget: string }
      - label: "Opciones"
        name: "settings"
        file: "src/_data/settings.yaml"
        fields:
          - { label: Nombre del sitio, name: site, widget: string }
          - { label: Descripcion, name: description, widget: string }
          - { label: URL, name: url, widget: string }
